language: scala

script:
  "sbt -Dconfig.file=./conf/application_test.conf ++$TRAVIS_SCALA_VERSION clean coverage test coverageReport"

after_success:
  - bash <(curl -s https://codecov.io/bash)

scala:
- 2.13.0
- 2.13.1

jdk:
- openjdk11
