language: scala

script:
  "sbt ++$TRAVIS_SCALA_VERSION clean coverage test coverageReport"

after_success:
  - bash <(curl -s https://codecov.io/bash)

scala:
- 2.12.8

jdk:
- openjdk11
