---
swagger: "2.0"
info:
  title: "The Hand"
  description: "API endpoints documentation"
consumes:
- application/json
produces:
- application/json
securityDefinitions:
  apiKey:
    type: apiKey
    in: header
    name: X-API-Key
    description: Requests should pass an X-API-Key header.
  apiToken:
    type: apiKey
    in: header
    name: X-AUTH-Token
    description: Corresponding Auth Token X-AUTH-Token (only for secured requests)
    required: false
security:
- apiKey: []
- apiToken: []