---
swagger: "2.0"
info:
  title: "The Hand"
  description: "API endpoints documentation"
consumes:
- application/json
produces:
- application/json
securityDefinitions:
  apiKey:
    type: apiKey
    in: header
    name: X-API-Key
    description: Requests should pass an X-API-Key header.
  apiDate:
    type: apiKey
    in: header
    name: Date
    description: Date time in format Thu, 07 Mar 2019 18:16:07 GMT
  apiAcceptLanguage:
    type: apiKey
    in: header
    name: Accept-Language
    description: Language abreviation en es pt (optional)
    required: false
  apiToken:
    type: apiKey
    in: header
    name: X-AUTH-Token
    description: Corresponding Auth Token X-AUTH-Token (only for secured requests)
    required: false
security:
- apiKey: []
  apiDate: []
- apiAcceptLanguage: []
- apiToken: []